ARG VERSION=1.6.1

FROM mariadb:10.5

ARG VERSION

# https://github.com/ctripcorp/apollo/raw/v${VERSION}/scripts/sql/apolloconfigdb.sql
# https://github.com/ctripcorp/apollo/raw/v${VERSION}/scripts/sql/apolloportaldb.sql
