server:
  port: 8762
spring:
  application:
    name: service-zuul
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: student-service
    api-b:
      path: /api-b/**
      serviceId: school-service
apollo:
  bootstrap:
    enable: true
    namespaces: zuul-config-apollo
  meta: http://localhost:8080
  cache-dir: /apollo